node {
    def mvnHome
    stage('Preparation') {
        git 'https://github.com/Magillem/bbl-ci-cd.git'
        mvnHome = tool 'M3'
    }
    stage('workspace check') {
        location = pwd()
        echo "Current location is ${location}"
    }
    stage('Build') {
        if (isUnix()) {
            sh "cd demo/uglycode; '${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
        } else {
            bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package/)
        }
    }
    stage('tests') {
        if (isUnix()) {
            sh "cd demo/uglycode; '${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore test"
        } else {
            bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore test/)
        }
                failFast: false
    }
    //add mvn sonar:sonar
    stage('Sonar') {
//       def scannerHome = tool 'SonarQube Scanner 2.8';
//       withSonarQubeEnv('SonarQube Server') {
//         sh "${scannerHome}/bin/sonar-scanner"
//       }
        withSonarQubeEnv('SonarQube Server') {
            if (isUnix()) {
                sh "cd demo/uglycode; '${mvnHome}/bin/mvn' sonar:sonar"
            } else {
                bat(/"${mvnHome}\bin\mvn" sonar:sonar/)
            }
        }
    }
}