node {
   def mvnHome
   stage('Preparation') {
      git 'https://github.com/Magillem/bbl-ci-cd.git'
      mvnHome = tool 'M3'
   }
   stage('workspace check') {
       location = pwd()
       echo "Current location is ${location}"
   }
   stage('Build') {
      if (isUnix()) {
         sh "cd demo/demo-rcp-tycho/com.mds.bbl.tycho; '${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
      } else {
         bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package/)
      }
   }
}