node {
withEnv(
    [
        "NODE_PATH=${tool 'nodejs'}",
        "MAVEN_OPTS=-Xmx4g",
        "PATH+MAVEN_AND_NODE=${tool 'nodejs'}/bin:${tool 'M3'}/bin",
        "LM_LICENSE_FILE=44242@mdsdev",
        "JENKINS_ENV=${env.JENKINS_ENV}",
        "JENKINS_TMP=${env.JENKINS_TMP}",
    ]) {

        stage('checkout') {
            checkout scm
        }

        stage('check tools') {
            sh "node -v"
            sh "npm -v"
            sh "bower -v"
            sh "gulp -v"
        }

        stage('npm install') {
            sh "npm install"
        }

        stage('clean') {
            sh "./gradlew clean"
        }

        stage('backend tests') {
            try {
                sh "./gradlew test"
            } catch(err) {
                throw err
            } finally {
                step([$class: 'JUnitResultArchiver', testResults: '**/build/**/TEST-*.xml'])
            }
        }

        stage('frontend tests') {
            try {
                sh "gulp test"
            } catch(err) {
                throw err
            } finally {
                step([$class: 'JUnitResultArchiver', testResults: '**/build/test-results/karma/TESTS-*.xml'])
            }
        }

        stage('packaging') {
            sh "./gradlew bootRepackage -Pprod -x test"
        }
    }
}
